/*
 * @file xbee.h
 * @author jbaker
 * @date 1/23/2012
 */

#ifndef XBEE_H_
#define XBEE_H_

// API frames
#define XBEE_API_AT_CMD							0x08
#define XBEE_API_AT_CMD_QUEUE_PARAMETER_VAL		0x09
#define XBEE_API_ZIGBEE_TX_REQ					0x10
#define XBEE_API_EXPLICIT_ADDR_ZIGBEE_CMD		0x11
#define XBEE_API_REMOTE_CMD_REQ					0x17
#define XBEE_API_CREATE_SRC_ROUTE				0x21
#define XBEE_API_AT_CMD_RESPONSE				0x88
#define XBEE_API_MODEM_STATUS					0x8A
#define XBEE_API_ZIGBEE_TX_STATUS				0x8B
#define XBEE_API_ZIGBEE_RX_PACKET				0x90
#define XBEE_API_ZIGBEE_EXPLICIT_RX_IND			0x91
#define XBEE_API_ZIGBEE_IO_DATA_SAMPLE_RX_IND	0x92
#define XBEE_API_XBEE_SENSOR_READ_IND			0x94
#define XBEE_API_NODE_ID_IND					0x95
#define XBEE_API_REMOTE_CMD_RESPONSE			0x97
#define XBEE_API_OTA_FIRMWARE_UPDATE_STATUS		0xA0
#define XBEE_API_ROUTE_RECORD_IND				0xA1
#define XBEE_API_MANY_TO_ONE_ROUTE_REQ_IND		0xA3

#endif /* XBEE_H_ */
